version: '3.9'
services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb

    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8000

#   src/main/resources/application.properties
#   spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#   spring.datasource.username=postgres
#   spring.datasource.password=password